### ISSUE TITLE
Exception的命名空间有问题，应该是Exception不是Exceptions，跟目录得一直

### ISSUE THREAD

**Issue by ww380459000** [luyisuifeng/aliyun-php-sdk-sms#1]

**Comment by luyisuifeng** [comment]
非常感谢您指出存在的问题，我会尽快修正

**Comment by ww380459000** [comment]
<php>
$endpoint       = new Endpoint("cn-hangzhou", $regionIds, $productDomains);
$endpoints      = array( $endpoint );
EndpointProvider::setEndpoints($endpoints);
</php>

这个最好再加个demo，我测试，这个得初始化。

**Comment by ww380459000** [comment]
参考demo
<php> 
  $endpoint = new Endpoint("cn-hangzhou", $regionIds, $productDomains);
$endpoints = array( $endpoint );
EndpointProvider::setEndpoints($endpoints);
   $iClientProfile = DefaultProfile::getProfile("cn-hangzhou", "your accessKey", "your accessSecret");  
    $client = new DefaultAcsClient($iClientProfile);  
    $request = new Sms\SingleSendSmsRequest();
    $request->setSignName("验证测试");/_签名名称_/
    $request->setTemplateCode("SMS_11111");/_模板code_/
    $request->setRecNum("手机号");/_目标手机号_/
    $request->setParamString("{\"name\":\"sanyou\"}");/_模板变量，数字一定要转换为字符串_/
    try {
        $response = $client->getAcsResponse($request);
        print_r($response);
    }
    catch (ClientException  $e) {
        print_r($e->getErrorCode());  
        print_r($e->getErrorMessage());  
    }
    catch (ServerException  $e) {  
        print_r($e->getErrorCode());  
        print_r($e->getErrorMessage());
    }

</php>

**Comment by luyisuifeng** [comment]
demo就如你写的那样
